### ISSUE TITLE
c error

### ISSUE THREAD

**Issue by githbob** [TreborNamor/TradingView-Machine-Learning-GUI#19]
Firefox profile has been filled in, but the prompt is as follows
WebDriver Error: Please Check Your FireFox Profile Path Is Correct.
Find Your Firefox Path Instructions. https://imgur.com/gallery/rdCqeT5

**Comment by TreborNamor** [comment]
Sometimes there is more than one Firefox path. Try the alternative one if
the first one did not work. As well, can you type the path here so I can
see if there is an error with the format.
