### ISSUE TITLE
The browser takes up too much memory

### ISSUE THREAD

**Issue by githbob** [TreborNamor/TradingView-Machine-Learning-GUI#22]
After running for a period of time, the browser occupies too much memory. and the program stops automatically. Is there a good solution?

**Comment by TreborNamor** [comment]
Hi, this is Multiprocessing which is normal, but if you are having slowness/hanging issues, try reducing the number of multiprocesses: Go to Settings > General - Performance, then deselect 'Use recommended performance settings' and change 'Content process limit' to a smaller number - try 1. See - Firefox's performance settings, and Startup, home page, tabs, and download settings.
