### ISSUE TITLE
cross bug of MACD RSI Strategy

### ISSUE THREAD

**Issue by hatawong** [TreborNamor/TradingView-Machine-Learning-GUI#23]
wrong cross
`crossover_bear = crossunder(signal_line, macd_line)`

right cross
`crossover_bear = crossunder(macd_line, signal_line)`

**Comment by TreborNamor** [comment]
thank you for address this error. I fixed the script right now

**Comment by hatawong** [comment]
My pleasure! MACD with CSI is a brilliant and effective strategy
