### ISSUE TITLE
Parameters Bug

### ISSUE THREAD

**Issue by OzgunKB** [TreborNamor/TradingView-Machine-Learning-GUI#24]
I'm typing the maximum number 60, but it's also trying larger values. This issue did not exist in the non-GUI version.
![Ekran Alıntısı](https://user-images.githubusercontent.com/48881141/133314339-ef202917-9acb-47ee-955a-eba1132ba94f.PNG)

**Comment by TreborNamor** [comment]
It seems like my program may have a bug somewhere from the look of your long parameters. The Increment input box should of been disabled for Long & Short Optimizer like the picture below. What operating system are you running?
![image](https://user-images.githubusercontent.com/59729477/133553719-8f9c546d-bee0-479f-b448-3b0c1a2f3656.png)

**Comment by OzgunKB** [comment]
Yes, I tried changing the source codes. There is still the problem that I wrote above. Windows 10 and Python x64.

**Comment by TreborNamor** [comment]
On your Windows machine, go to Registry Editor and follow this path. Computer\HKEY_CURRENT_USER\Software\TradingviewOptimizer\Strategy Parameters

Inside the Strategy Parameters is where your parameter data is being stored. If you make a change to any parameter on the app and then refresh Registry Editor it will show the new value. Try checking what values are stored inside there and if they match what is on the app. As well, do you have a link to the strategy your using on TradingView? I'll take a look at it
![image](https://user-images.githubusercontent.com/59729477/133670303-c89399ff-24c1-4ad8-be83-ca6f3cc508d2.png)

**Comment by OzgunKB** [comment]
Can you watch the video?
[https://www.youtube.com/watch?v=_XTyDfw3bKE](url)

**Comment by thedelph** [comment]
I'm getting a similar issue. Rather than modify the TP/SL parameters it's adjusting some other parameters for me EMA & Wavetrend channel lengths.
