### ISSUE TITLE
Any reason for adding the binary exe to the repo instead of compile instructions?

### ISSUE THREAD

**Issue by milankubin** [TreborNamor/TradingView-Machine-Learning-GUI#30]
Can you tell me the reasoning behind putting the exe in the repo instead of adding compilation instructions to the readme?
I can understand that maybe you don't want to write python for the web, but I'm always very cautious with binaries, and it's not a very common practice in open source to add binaries to repos (unless maybe DLL's so forth).

Users should be able to verify the source and compile it from source, and avoid any malware suspicion.
I see this a lot - with crypto particularly. 

Can you add the compilation instructions to the readme?

**Comment by AmitKehat** [comment]
Hi, It could be helpful for me as well.
I have an issue - the software captures the optimization's results too fast, before the new result's calculations where ended. So I have 10 backtestings with different input parameters but with the same net porfit in a row.
I added a short delay before the results are captured and it solve the issue, but I don't know how to repackage it to work as the original.
I tried 'pyinstaller', but it doesn't work as expected.

Help please.
