### ISSUE TITLE
Web elements 

### ISSUE THREAD

**Issue by moehawk** [TreborNamor/TradingView-Machine-Learning-GUI#52]
Having an issue finding finding the buttons, i think tradingview has changed things around

https://gyazo.com/8b530c95ccfca2b84011c98c9f655e96

**Comment by TreborNamor** [comment]
thanks for reaching out. It turns out alot of the web elements did change. I just fixed the issue right now.

**Comment by toritotony** [comment]
I had this problem yesterday, I see this issue was resolved, however I keep receiving the error mentioned initially (running the updated code)
