### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by DriesVR1232** [TreborNamor/TradingView-Machine-Learning-GUI#53]
Hello, this is more a question rather than an issue. Is it possible to change this to test other strategies? I saw it somewhere but the github page does not exist. Also how fast is it to test 1000 cycles for example?

**Comment by TreborNamor** [comment]
thanks for reaching out to me about the link issues you were having on documentation. The links are now working again. You can create a custom strategy easily following the instructions from one of the links in the documentation. The time it takes to cycle through 1000 attempts is based on internet speed and pc hardware. On my pc, it will complete 1 attempt about every two seconds.

**Comment by DriesVR1232** [comment]
Oke and i can oalso test invite only scripts that i have access to right?

**Comment by TreborNamor** [comment]
you can test the ones i have created or create your own strategy using the tradingview strategy template in the tv_strategies folder
