### ISSUE TITLE
Problem at startup

### ISSUE THREAD

**Issue by Andreymyski** [TreborNamor/TradingView-Machine-Learning-GUI#54]
Hello, I did everything as it says in your instructions, but when I press RUN, CMD starts working, but the program freezes. And in the end, such mistakes come out, tell me what to do.

Could Not Click Strategy Tester Tab. Please Check web elements class name in commands.py file.
Could Not click Overview Tab. Please Check web elements class name in commands.py file.
Could not click settings button. Please check web_elements in commands.py file.
Could not input tab button. Please check web_elements in commands.py file.
Traceback (most recent call last):
  File "TradeViewGUI.py", line 153, in optimize_longs_shorts
    Optimize Longs Shorts.Long Short Script()
  File "scripts\OptimizeLongsShorts.py", line 21, in __init__
    self.run_script()
  File "scripts\OptimizeLongsShorts.py", line 37, in run_script
    self.click_enable_both_checkboxes()
  File "web_commands\commands.py", line 246, in click_enable_both_checkboxes

IndexError: list index out of range

![8bc8ca5e5fed7d59a770ca218bd9dfe1](https://user-images.githubusercontent.com/116179517/196708822-08b29c54-8889-4fda-93a2-36e30975ceea.jpg)

**Comment by Andreymyski** [comment]
I downloaded everything yesterday. I didn't change anything, I did everything according to the instructions

**Comment by TreborNamor** [comment]
I'll take a look at the code to see if things are still running correctly.
That error "couldn't click settings button" is when the program is having
trouble clicking the settings button on webpage. It could be an error on my
code or it could be that the trading view strategy is unreachable

**Comment by Andreymyski** [comment]
I checked on different strategies, both on my own and on others that are closed, the result is the same. Maybe I need to install some libraries or something else?

**Comment by Andreymyski** [comment]
As I understand it, I'm fine. I've tried everything I can. Apparently Tradingview has changed something again.

**Comment by maximus728** [comment]
I'm getting the exact same error. Did someone find a solution to this ?

**Comment by Andreymyski** [comment]
Yes, I found it. I don't use the program itself to run, but its python code in visual studio. After running the code, the program also runs, but without errors.

**Comment by maximus728** [comment]
That worked for me. Thanks! I still get this error:
"Could not input tab button. Please check web_element's in commands.py file."

and it takes quite a while to finish, which I guess is normal with the default settings (0/30)

**Comment by Andreymyski** [comment]
Install all dependencies:
pip install -r requirements.txt

**Comment by maximus728** [comment]
It is running now and doing its thing in firefox. but it seems to run forever, even with very simple parameters/settings (min stoploss 1 max stoploss 2 and 0 decimals). I also don t get the status updates in the CMD, Any Idea why that happens ?
![image](https://user-images.githubusercontent.com/118347859/202484718-98d62bb3-9eb6-4a58-acde-5213e2b6d5b6.png)

**Comment by Andreymyski** [comment]
I don't know. I get the results in visual studio itself

**Comment by maximus728** [comment]
Ok thank your for your help!
